In [0]:
import tensorflow as tf
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.models import Model
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM, GRU
from keras.layers import Input,SpatialDropout1D, Embedding, LSTM, Dense, merge, Convolution2D, Lambda, GRU, TimeDistributed, Reshape, Permute, Convolution1D, Masking, Bidirectional
from keras.optimizers import Adam
from keras.layers import concatenate
from keras.regularizers import l2
from keras.callbacks import ModelCheckpoint
from keras import optimizers, callbacks

Using TensorFlow backend.


In [0]:
from tensorflow.python.client import device_lib
import gzip
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 8563469937773754960
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 14659868280580666135
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 1856340038973861217
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14892338381
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10530835377830656194
physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
]


In [0]:
# Install the PyDrive wrapper & import libraries.\n# This only needs to be done once per notebook.\n!pip install -U -q PyDrive\nfrom pydrive.auth import GoogleAuth\nfrom pydrive.drive import GoogleDrive\nfrom google.colab import auth\nfrom oauth2client.client import GoogleCredentials\n\n# Authenticate and create the PyDrive client.\n# This only needs to be done once per notebook.\nauth.authenticate_user()\ngauth = GoogleAuth()\ngauth.credentials = GoogleCredentials.get_application_default()\ndrive = GoogleDrive(gauth)\n\n# Download a file based on its file ID.\n#\n# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz\nfile_id = \'REPLACE_WITH_YOUR_FILE_ID\'\ndownloaded = drive.CreateFile({\'id\': file_id})\nprint(\'Downloaded content "{}"\'.format(downloaded.GetContentString()))'

In [0]:
!git clone https://github.com/pythonLoader/Lula_Dataset.git
!git clone https://github.com/Arpita33/WeakILSDataset.git

fatal: destination path 'Lula_Dataset' already exists and is not an empty directory.
Cloning into 'WeakILSDataset'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 1), reused 4 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), done.


In [0]:
import numpy as np

In [0]:
# Train_data_X_arr = np.load("Lula_Dataset/Train_array.npy")
# Train_data_Y_arr = np.load("Lula_Dataset/Valid_array.npy")

Train_data_X_arr = np.load("WeakILSDataset/weak_ILS_train_tree.npy")
Train_data_Y_arr = np.load("WeakILSDataset/weak_ILS_valid_tree.npy")

#Train_data_X_arr = 

print(Train_data_X_arr.shape)
print(Train_data_Y_arr.shape)

(3900, 165, 3)
(3900, 165, 3)


In [0]:
for i in range(Train_data_X_arr.shape[1]):

  print(f'{Train_data_X_arr[0][i]} and {Train_data_Y_arr[0][i]}')

[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 0. 1.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 0. 1.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 0. 1.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 1. 0.]
[0. 0. 0.] and [0. 0. 1.]
[0. 0. 0.] and [1. 0. 0.]
[0. 0. 0.] and [0. 0. 1.]
[0. 0. 0.] a

In [0]:
gene_tree_num = Train_data_X_arr.shape[0]
triplet = 3
print(gene_tree_num)

3900


In [0]:
x = Train_data_X_arr[0][:40]
y = Train_data_Y_arr[0][:40]

print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
Train_data_X_reshaped = Train_data_X_arr.reshape(Train_data_X_arr.shape[1],Train_data_X_arr.shape[0]*Train_data_X_arr.shape[2])

print(Train_data_X_arr[1][0]);

[1. 0. 0.]


In [0]:
print(Train_data_X_reshaped.shape)

print(Train_data_X_reshaped[0])

(165, 11700)
[0. 0. 0. ... 0. 1. 0.]


In [0]:
no_of_gene_trees=int(Train_data_X_reshaped.shape[1]/3)
three_taxa_seq=Train_data_X_reshaped.shape[0]
mask=[]
for i in range (0,three_taxa_seq):
  arr=Train_data_X_reshaped[i]
  mask_row=[]
  for j in range (0,no_of_gene_trees):
    start=j*3
    sum=0
    
    for k in range(start,start+3):
      sum+=arr[k]
      
    mask_row.append(sum)    
  
  mask.append(mask_row)
np_mask=np.array(mask)
print(np_mask.shape)
print(np_mask[0])
#print(nmsk.shape)
#return nmsk
#print(nmsk[0][1])
#print(nmsk.dtype)

(165, 3900)
[0. 0. 0. ... 1. 1. 1.]


In [0]:
def custom_accuracy_function(mask):
    # mask: ekta binary mask e.g [1,0,1,0,1,1,1]
    # 0 gula missing data represent kore
    def custom_accuracy(y_true, y_predict):
        y_pred_labels = K.cast(K.argmax(y_predict, axis=2), 'float32')
        y_true_labels = K.cast(K.argmax(y_true, axis=2), 'float32')
        is_same = K.cast(K.equal(
            y_true_labels, y_pred_labels), 'float32')
        num_same = K.cast(K.sum(is_same * mask, axis=1), 'float32')
        lengths = K.cast(K.sum(mask, axis=1), 'float32')
        return K.mean(num_same / lengths, axis=0)
      
    return custom_accuracy

def custom_loss_function(mask):
    def custom_loss(y_true, y_predict):
        y_pred_labels = K.cast(K.argmax(y_predict, axis=2), 'float32')
        y_true_labels = K.cast(K.argmax(y_true, axis=2), 'float32')
        is_same = K.cast(K.equal(
            y_true_labels, y_pred_labels), 'float32')
        num_same = K.cast(K.sum(is_same * mask, axis=1), 'float32')
        lengths = K.cast(K.sum(mask, axis=1), 'float32')
        return K.cast(1-K.mean(num_same / lengths, axis=0), 'float32')
      
    return custom_loss


In [0]:
from keras.layers import Embedding, Add, concatenate, Input, Softmax
from keras import backend as K
#keras.activations.softmax(x, axis=-1)
from keras.activations import softmax



def get_model(input_size):
  
  Input_layer = Input(batch_shape=(None,input_size), name='main_input')
  
  encoder_layer_1 = Dense(int(input_size//1.5), activation='relu', use_bias=True) (Input_layer)
  encoder_layer_2 = Dense(int(input_size//2), activation='relu', use_bias=True) (encoder_layer_1)
  encoder_layer_3 = Dense(int(input_size//2.5), activation='relu', use_bias=True) (encoder_layer_2)
  
  encoder_layer_4 = Dense(int(input_size//3), activation='relu', use_bias=True) (encoder_layer_3)
  encoder_layer_5 = Dense(int(input_size//4), activation='relu', use_bias=True) (encoder_layer_4)
  decoder_layer_0 = Dense(int(input_size//3), activation='relu', use_bias=True) (encoder_layer_5)
  
  decoder_layer_1 = Dense(int(input_size//2.5),activation='relu',use_bias=True) (decoder_layer_0)
  decoder_layer_2 = Dense(int(input_size//2),activation='relu',use_bias=True) (decoder_layer_1)
  decoder_layer_3 = Dense(int(input_size//1.5),activation='relu',use_bias=True) (decoder_layer_2)
  decoder_layer_4 = Dense(input_size,activation='relu',use_bias=True) (decoder_layer_3)
  
  decoder_output = decoder_layer_4
  
  reshaped = Lambda( lambda x: K.reshape(x, (-1, int(decoder_output.shape[1]//3), 3)))(decoder_output)
  
  print(f'Reshaped Shape = {reshaped.shape}')
  
  final_decoded_layer_output = Softmax(axis=-1)(reshaped)
  
  autoencoder = Model(Input_layer, final_decoded_layer_output)
  encoder  = Model(Input_layer,encoder_layer_4)
  #decoder = Model(encoder_layer_4,final_decoded_layer_output)
  
  return autoencoder,encoder

In [0]:
autoencoder, encoder = get_model(input_size=gene_tree_num*triplet)

autoencoder.summary()

W0804 05:40:14.248952 139832055019392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0804 05:40:14.259986 139832055019392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0804 05:40:14.261701 139832055019392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



Reshaped Shape = (?, 3900, 3)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
main_input (InputLayer)      (None, 11700)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 7800)              91267800  
_________________________________________________________________
dense_2 (Dense)              (None, 5850)              45635850  
_________________________________________________________________
dense_3 (Dense)              (None, 4680)              27382680  
_________________________________________________________________
dense_4 (Dense)              (None, 3900)              18255900  
_________________________________________________________________
dense_5 (Dense)              (None, 2925)              11410425  
_________________________________________________________________
dense_6 (Dense)              (None, 3900)     

In [0]:
Train_data_X_3D_reshaped = Train_data_X_arr.reshape(Train_data_X_arr.shape[1],Train_data_X_arr.shape[0],Train_data_X_arr.shape[2])

print(Train_data_X_arr.shape)

(3900, 165, 3)


In [0]:

autoencoder.compile(optimizer='adam', 
                   loss='binary_crossentropy',
                   sample_weight_mode='temporal',
                   metrics=[custom_accuracy_function(mask=np_mask)])

W0804 05:40:14.426419 139832055019392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0804 05:40:14.455226 139832055019392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0804 05:40:14.462162 139832055019392 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [0]:
autoencoder.fit(x=Train_data_X_reshaped,
               y=Train_data_X_3D_reshaped,
               epochs=1000,
               batch_size=165,
               shuffle=True,
               verbose=1)

W0804 05:40:14.867138 139832055019392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/1000
165/165 [==============================] - 10s 61ms/step - loss: 0.5728 - custom_accuracy: 0.3591
Epoch 2/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.5705 - custom_accuracy: 0.4149
Epoch 3/1000
165/165 [==============================] - 0s 2ms/step - loss: 1.1775 - custom_accuracy: 0.4311
Epoch 4/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.5727 - custom_accuracy: 0.4184
Epoch 5/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.5725 - custom_accuracy: 0.4029
Epoch 6/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.5717 - custom_accuracy: 0.4175
Epoch 7/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.5700 - custom_accuracy: 0.4212
Epoch 8/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.6969 - custom_accuracy: 0.4467
Epoch 9/1000
165/165 [==============================] - 0s 2ms/step - loss: 0.5723 - custom_accuracy: 0.4459
Epoch 10/1000
165

In [0]:
y_hat = autoencoder.predict(Train_data_X_reshaped)

In [0]:
print(y_hat.shape)

#print(Train_data_Y_arr.shape)
Y_arr = Train_data_Y_arr.reshape(Train_data_Y_arr.shape[1],Train_data_Y_arr.shape[0],Train_data_Y_arr.shape[2])
#print(Y_arr.shape)
for x in range(0,y_hat.shape[1]):

  print(str(Train_data_X_3D_reshaped[0][x]) + str(y_hat[0][x]) + " " + str(Y_arr[0][x]))

(165, 3900, 3)
[0. 0. 0.][0.6707814  0.16460931 0.16460931] [1. 0. 0.]
[0. 0. 0.][0.19701305 0.19701305 0.6059739 ] [1. 0. 0.]
[0. 0. 0.][0.6160524  0.19197382 0.19197382] [0. 0. 1.]
[0. 0. 0.][0.16302067 0.6739587  0.16302067] [1. 0. 0.]
[0. 0. 0.][0.5346946  0.20089665 0.2644088 ] [0. 1. 0.]
[0. 0. 0.][0.18816648 0.623667   0.18816648] [1. 0. 0.]
[0. 0. 0.][0.17035788 0.6592842  0.17035788] [0. 1. 0.]
[0. 0. 0.][0.58656347 0.20671831 0.20671831] [1. 0. 0.]
[0. 0. 0.][0.6916513  0.15417439 0.15417439] [0. 1. 0.]
[0. 0. 0.][0.16473566 0.16473566 0.67052865] [1. 0. 0.]
[0. 0. 0.][0.60842437 0.19578785 0.19578785] [0. 0. 1.]
[0. 0. 0.][0.18768871 0.6246225  0.18768871] [1. 0. 0.]
[0. 0. 0.][0.33333334 0.33333334 0.33333334] [0. 1. 0.]
[0. 0. 0.][0.17432937 0.6513412  0.17432937] [1. 0. 0.]
[0. 0. 0.][0.1929264 0.6141472 0.1929264] [0. 1. 0.]
[0. 0. 0.][0.62984055 0.18507974 0.18507974] [1. 0. 0.]
[0. 0. 0.][0.61802155 0.19098923 0.19098923] [0. 1. 0.]
[0. 0. 0.][0.20253968 0.5949207  0.2